
gd_sam2:
  MODEL_ID: IDEA-Research/grounding-dino-tiny
  PROMPT_TYPE_FOR_VIDEO: box # choose from ["point", "box", "mask"]
  sam2_checkpoint: grounded_sam_2/checkpoints/sam2.1_hiera_large.pt
  model_cfg: configs/sam2.1/sam2.1_hiera_l.yaml
  gd_sam2_generate_results: results/gd_sam2_generate_results.csv


paths:
  # data_dir: /path/to/data
  working_dir: working_dir
  working_dir_gd_sam: working_dir/tracking
  working_dir_gd_sam_img: working_dir/img
  working_dir_gd_sam_masks_only: working_dir/masks_only
  results_path: results
  video_results_path: results/videos
  segmented_class_results: results/segmented_classes

dataset_paths:
  video_dir: /path/to/dir
  class_dir: synth_data_gen/STARSS23_CLASSES.txt

max_vid_seg: 15

# result_files:

# features:
#   enable_feature_x: true
#   max_items: 100